#
# File:    ./pyproject.toml
# Author:  Jiří Kučera <sanczes AT gmail.com>
# Date:    2021-01-31 01:00:32 +0100
# Project: pyproject-template: A cookiecutter template for Python projects
# Brief:   Configuration for python linters
#
# SPDX-License-Identifier: MIT
#

[tool.black]
line-length = 79

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 79

[tool.pylint.design]
min-public-methods = 0

[tool.pylint.format]
max-line-length = 79

[tool.pylint."message control"]
# Disable not PEP 8 compliant warnings:
#   C0330: Wrong hanging indentation before block (add 4 spaces)
#   C0326: Bad whitespace
disable = ["C0330", "C0326"]
